### PR TITLE
break docker build cache based on time stamp

### PR DESCRIPTION
**Pull request by cguentherTUChemnitz**
Hi there,

i like your container providing easy access to strut. Nevertheless i would suggest you to add an environment variable right after the 'FROM' statement. Like this:

``` yml
FROM node:4.1.0-slim
ENV REFRESHED_AT 2015_02_20
```

It shows at which date your image is updated. It is beneficial especially when you provide access to an master-branch project. So you can update this environment variable and your automatic build in docker hub is triggered with this time-stamped master-branch checkout.

Additionally other users can provide pull requests, updating this environment variable to generate a new master snapshot.

### CODE REVIEW

**Comment by blyoa** [comment]
Thank you for your pull request and detailed explanation!

**Comment by blyoa** [comment]
Oops, 2015 has already ended. Could you update your pull request?

**Comment by cguentherTUChemnitz** [comment]
You are total right :) It is now changed to 2016 ^^

**Comment by blyoa** [comment]
Thanks!

**Pull request merged**
